version: '3.8'

services:
  nats:
    image: nats:2.9.20-alpine3.18
    container_name: nats-server
    ports:
      - "4222:4222" # Puerto del cliente
      - "8222:8222" # Puerto de monitoreo/HTTP
    command: -js

  postgres:
    image: postgres:15-alpine
    container_name: iot-postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: iot_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: